version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./deploy/nginx.default.conf:/etc/nginx/conf.d/default.conf"
      - "./web:/var/www/html"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always
    env_file:
      - ".env"
    depends_on:
      - php
      - mysqldb
  php:
    build: .
    restart: always
    env_file:
      - ".env"
    volumes:
      - "./deploy/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./web:/var/www/html"
  composer:
    image: composer:2.2.3
    volumes:
      - "./web:/app"
    command: install
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT=${MYSQL_PORT}
    ports:
      - 8989:${MYSQL_PORT}
    volumes:
      - "./data/db/mysql:/var/lib/mysql"